### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AnnaVydrak** [AnnaVydrak/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Anna124321** [comment]
just intro example for Binary Studio Academy 2020. just intro example for Binary Studio Academy 2020. just intro example for Binary Studio Academy 2020. just intro example for Binary Studio Academy 2020. just intro example for Binary Studio Academy 2020.
