### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AnnaVydrak** [AnnaVydrak/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Anna124321** [comment]
https://www.instagram.com/realdonaldtrump/
https://www.facebook.com/DonaldTrump/
//other links
