### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AnnaVydrak** [AnnaVydrak/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Anna124321** [comment]
2001
timeline 2001
2002
timeline 2002
2003
timeline 2003
2004
timeline 2004
2005
timeline 2005
2006
timeline 2006
2007
timeline 2007
2008
timeline 2008
2009
timeline 2009
2010
timeline 2010
2011
timeline 2011
2018
timeline 2018
2020
timeline 2020
